BookNest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("",include("library.urls") ),
    path("accounts/",include("accounts.urls")),
    path('admin/', admin.site.urls),
    
]

accounts/urls.py
from django.urls import path
from .import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path("logout/" , views.logout_view , name = "logout")
]

library/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
import static

urlpatterns = [
    path("", views.index, name = "index"),
    path('cart/', views.view_cart, name='view_cart'),
    path('borrow_books/', views.borrow_books, name='borrow_books'),
    path('results/', views.results, name='results'),
    path('view_borrowing_history/', views.view_borrowing_history, name='view_borrowing_history'),
    path('add_to_cart/<int:book_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

from django.contrib.auth.models import AbstractUser

# Create your models here.

# User Model
# class User(models.Model):
#     computerNumber = models.CharField(max_length=50 , unique=True)
#     username = models.CharField(max_length=50, unique=True)
#     password = models.CharField(max_length=255)  # Store hashed and salted passwords
#     email = models.EmailField(unique=True)
#     first_name = models.CharField(max_length=50, blank=True, null=True)
#     last_name = models.CharField(max_length=50, blank=True, null=True)
   

#     def __str__(self):
#         return self.username
    
# #Genre
# class Genre(models.Model):
#     genre = models.CharField(max_length=50, blank=True, null=True)
#     topic = models.CharField(max_length=50, blank=True, null=True)

#     def __str__(self):
#         name = self.genre
#         return name
    

# Book Model
class Candidate(models.Model):
   
    title = models.CharField(max_length=255)
    position = models.CharField(max_length=50, blank=True, null=True)
    slogan = models.TextField(blank=True, null=True)
    book_picture = models.ImageField(upload_to='static/images', blank= True , null= True)

    def __str__(self):
        return self.title

# BorrowingHistory Model
class BorrowingHistory(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    book = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    borrowed_date = models.DateField()
    due_date = models.DateField()
    return_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.user}  borrowed  {self.book}  on  {self.borrowed_date}"

    

# UserRecommendation Model
class UserRecommendation(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    book = models.ForeignKey(Candidate, on_delete=models.CASCADE)



# ForumPost Model
class ForumPost(models.Model):
    forumid = models.AutoField(primary_key= True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    topic = models.CharField(max_length=50, blank=True, null=True)
    # comment = models.CharField(max_length=255 , blank= True , null= True )

    def __str__(self):
        return self.title
    

class Contact(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    message = models.CharField(max_length=500)

    def __str__(self):
        return f"Name : {self.name} ,  Phone : {self.phone},  Email : {self.phone},  Message : {self.message}"

class Comments(models.Model):
    comments = models.CharField(max_length=255)
    forumid= models.ForeignKey(ForumPost ,on_delete=models.CASCADE , blank = True , null = True )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    

    def __str__(self):
        return f"{self.comments} by {self.user.username}"
    

class CartItem(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    book = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s Cart Item: {self.book.title}"

class Profile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    computerNumber = models.CharField(max_length=50 , unique=True)
    

    def __str__(self):
        return f"{self.comments} by {self.user.username}"

library/forms.py
# forms.py
from django import forms
from . import models

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comments
        fields = ['comments']
        
        #Compare this snippet from BookNest/library/templates/library/forum_details.html:
class AddPost(forms.ModelForm):
    class Meta:
        model = models.ForumPost
        fields = ['title','topic','content']

#Contact Form

class Contact(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = ['name','phone','email','message' ]
        
#Search Form
class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False)
        

library/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .models import Candidate , ForumPost , User , Comments , Contact , CartItem ,BorrowingHistory , Profile
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from . import forms
from django.utils import timezone
from .forms import SearchForm
from django.db.models import Count


# Create your views here.
@login_required(login_url='/accounts/signup/')
def index(request):
    return render(request , "library/index.html",{
        "books" : Candidate.objects.all(),
        "forums" : ForumPost.objects.all()
    })


@login_required(login_url='/accounts/signup/')
def books(request):
    return render(request , "library/books.html" ,{
        "books" : Candidate.objects.all()
    })
 

###Cart Items
@login_required(login_url='/accounts/signup/')
def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    return render(request, 'library/cart.html', {'cart_items': cart_items})

@login_required(login_url='/accounts/signup/')
def add_to_cart(request, book_id):
    book = Candidate.objects.get(id=book_id)
    cart_item = CartItem(user=request.user, book=book)
    cart_item.save()
    return redirect('view_cart')

@login_required(login_url='/accounts/signup/')
def remove_from_cart(request, cart_item_id):
    cart_item = CartItem.objects.get(id=cart_item_id)
    cart_item.delete()
    return redirect('view_cart')

###### Borrowing books


@login_required(login_url='/accounts/signup/')
def borrow_books(request):
    cart_items = CartItem.objects.filter(user=request.user)
    current_date = timezone.now().date()
    due_date = current_date + timezone.timedelta(days=14)  # You can adjust the due date as needed.

    for cart_item in cart_items:
        book = cart_item.book
        BorrowingHistory.objects.create(user=request.user, book=book, borrowed_date=current_date, due_date=due_date)
        book.availability = False
        book.save()

    # Clear the user's cart after borrowing.
    cart_items.delete()

    return redirect('view_borrowing_history')  # You can create a view for viewing borrowing history.

###### Borrowing History
@login_required(login_url='/accounts/signup/')
def view_borrowing_history(request):
    # Retrieve the borrowing history for the current user
    borrowing_history = BorrowingHistory.objects.filter(user=request.user).order_by('-borrowed_date')

    # Render the borrowing history in a template
    return render(request, 'library/borrowing_history.html',{'borrowing_history': borrowing_history})



def results(request):
    # Query the database to get the total items borrowed for each candidate
    candidates = Candidate.objects.annotate(total_borrowed=Count('borrowinghistory'))
    
    # Pass the candidates data to the template
    return render(request, 'library/results.html', {'candidates': candidates})

library/templates/library/borrowing_history.html
{% extends "library/layout.html" %}
{% load static %}

{% block body %}
<div class="container">
    <h2>You Have Successfully Voted For </h2>

     
         
             
   
        {% for entry in borrowing_history %}
         
             {{ entry.book.title }}
             {{ entry.book.slogan }} 
             <br>
             {{ entry.position}} 
             
         

        <hr>
        {% endfor %}
        <form class="site-form" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %} {{ form }} {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"> {% endif %}
            <br>
            <input style="margin-top:1rem;"  class = "btn btn-primary w-100" type="submit" value="Finish">
        </form>
    
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

library/templates/library/cart.html
{% extends "library/layout.html" %}
{% load static %}

{% block body %}

<div class="container" >
    <h2>Your Votes</h2>

{% if cart_items %}

        {% for item in cart_items %}
        {{ item.book.title }}
       
        {{ item.book.slogan }}
        <br>
        {{ item.book.position }}
        <br>
                <a href="{% url 'remove_from_cart' item.id %}"><button class="btn btn-outline-danger btn-sm" type="submit">Remove</button></a>
            
                <hr>
        {% endfor %}
   
<a href="{% url 'borrow_books' %}"><button class="btn btn-primary btn-sm" type="submit">Submit</button></a>
{% else %}
<p>Your have not yet voted</p>
{% endif %}

<a href="{% url 'index' %}"><button class="btn btn-outline-primary btn-sm" type="submit">Vote For Other Positions</button></a>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% endblock %}

library/templates/library/index.html
{% extends "library/layout.html" %}
{% load static %}

{% block body %}

<div class="container">
    <h1 style="margin-top: 1rem;">President</h1>
    <div class="row">
        
        {% for book in books %}
        {% if book.position == "President" %}
        <div class="col-md-6">
            
                <div class="card" style="margin-bottom: 1rem;margin-top: 1rem;"><img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
                    <div class="card-body">
                        <h4 class="card-title">{{ book.title }} {{ book.slogan }} </h4>
                        
                        <p class="card-text">Running for: {{ book.position }}</p>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_to_cart' book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
        </div>
        {% endif %}
        {% empty %}
        <p>
            No Candidates
        </p>
                    
                {% endfor %}
    </div>
<hr>
    <h1 style="margin-top: 1rem;"> Vice President</h1>
    <div class="row">
        
        {% for book in books %}
        {% if book.position == "Vice President" %}
        <div class="col-md-6">
            
                <div class="card" style="margin-bottom: 1rem;margin-top: 1rem;"><img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
                    <div class="card-body">
                        <h4 class="card-title">{{ book.title }} {{ book.slogan }}</h4>
                        
                        <p class="card-text">Running for: {{ book.position }}</p>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_to_cart' book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
        </div>
        {% endif %}
        {% empty %}
        <p>
            No Candidates
        </p>
                    
                {% endfor %}
    </div>
    <hr>
    <h1 style="margin-top: 1rem;">Secretary General</h1>
    <div class="row">
        
        {% for book in books %}
        {% if book.position == "Secretary General" %}
        <div class="col-md-6">
            
                <div class="card" style="margin-bottom: 1rem;margin-top: 1rem;"><img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
                    <div class="card-body">
                        <h4 class="card-title">{{ book.title }} {{ book.slogan }}</h4>
                        
                        <p class="card-text">Running for: {{ book.position }}</p>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_to_cart' book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
        </div>
        {% endif %}
        {% empty %}
        <p>
            No Candidates
        </p>
       
                    
                {% endfor %}
    </div>
    <hr>
    <h1 style="margin-top: 1rem;">Academic Secretary</h1>
    <div class="row">
        
        {% for book in books %}
        {% if book.position == "Academic Secretary" %}
        <div class="col-md-6">
            
                <div class="card" style="margin-bottom: 1rem;margin-top: 1rem;"><img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
                    <div class="card-body">
                        <h4 class="card-title">{{ book.title }} {{ book.slogan }}</h4>
                        
                        <p class="card-text">Running for: {{ book.position }}</p>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_to_cart' book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
        </div>
        {% endif %}
        {% empty %}
        <p>
            No Candidates
        </p>
       
                    
                {% endfor %}
    </div>
    <hr>
    <h1 style="margin-top: 1rem;">Projects Coordinator</h1>
    <div class="row">
        
        {% for book in books %}
        {% if book.position == "Projects Coordinator" %}
        <div class="col-md-6">
            
                <div class="card" style="margin-bottom: 1rem;margin-top: 1rem;"><img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
                    <div class="card-body">
                        <h4 class="card-title">{{ book.title }} {{ book.slogan }}</h4>
                        
                        <p class="card-text">Running for: {{ book.position }}</p>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_to_cart' book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
        </div>
        {% endif %}
        {% empty %}
        <p>
            No Candidates
        </p>
       
                    
                {% endfor %}
    </div>
    <hr>
    <h1 style="margin-top: 1rem;">Treasurer</h1>
    <div class="row">
        
        {% for book in books %}
        {% if book.position == "Treasurer" %}
        <div class="col-md-6">
            
                <div class="card" style="margin-bottom: 1rem;margin-top: 1rem;"><img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
                    <div class="card-body">
                        <h4 class="card-title">{{ book.title }} {{ book.slogan }}</h4>
                        
                        <p class="card-text">Running for: {{ book.position }}</p>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_to_cart' book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
        </div>
        {% endif %}
        {% empty %}
        <p>
            No Candidates
        </p>
       
                    
                {% endfor %}
    </div>
    <hr>
    <h1 style="margin-top: 1rem;">Publicity Secretary</h1>
    <div class="row">
        
        {% for book in books %}
        {% if book.position == "Publicity Secretary" %}
        <div class="col-md-6">
            
                <div class="card" style="margin-bottom: 1rem;margin-top: 1rem;"><img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
                    <div class="card-body">
                        <h4 class="card-title">{{ book.title }} {{ book.slogan }}</h4>
                        
                        <p class="card-text">Running for: {{ book.position }}</p>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_to_cart' book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
        </div>
        {% endif %}
        {% empty %}
        <p>
            No Candidates
        </p>
       
                    
                {% endfor %}
    </div>
    <hr>
    <h1 style="margin-top: 1rem;">Executice Committee Member</h1>
    <div class="row">
        
        {% for book in books %}
        {% if book.position == "Executice Committee Member" %}
        <div class="col-md-6">
            
                <div class="card" style="margin-bottom: 1rem;margin-top: 1rem;"><img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
                    <div class="card-body">
                        <h4 class="card-title">{{ book.title }} {{ book.slogan }}</h4>
                        
                        <p class="card-text">Running for: {{ book.position }}</p>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_to_cart' book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
        </div>
        {% endif %}
        {% empty %}
        <p>
            No Candidates
        </p>
       
                    
                {% endfor %}
    </div>
    <br><br><br>
    <a href =  "{% url 'view_cart' %}" >
        <button class ="btn btn-primary w-100 "> View Your Votes </button>
    
    </a> 
</div>
<br><br><br><br><br><br>
   
{% endblock %}

library/templates/library/layout.html
{% load static %}
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>UNZAHSSA</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
</head>

<body>
    {% block body%} {% endblock %}
    <script src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/startup-modern.js'%}"></script>
</body>

</html>

library/templates/library/results.html
{% extends "library/layout.html" %}
{% load static %}

{% block body %}
<div class="container">
    <h1>President Results</h1>

    <ul>
        {% for candidate in candidates %}
        {% if candidate.position == "President" %}
            <li>
                {{ candidate.title }}: {{ candidate.total_borrowed }}
            </li>
        {% endif %}
        {% endfor %}
    </ul>
<hr>
    <h1>Vice President Results</h1>

    <ul>
        {% for candidate in candidates %}
        {% if candidate.position == "Vice President" %}
            <li>
                {{ candidate.title }}: {{ candidate.total_borrowed }}
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <hr>
    <h1>Secretary General Results</h1>

    <ul>
        {% for candidate in candidates %}
        {% if candidate.position == "Secretary General" %}
            <li>
                {{ candidate.title }}: {{ candidate.total_borrowed }}
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <hr>
    <h1>Academic Secretary Results</h1>

    <ul>
        {% for candidate in candidates %}
        {% if candidate.position == "Academic Secretary" %}
            <li>
                {{ candidate.title }}: {{ candidate.total_borrowed }}
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <hr>
    <h1>Projects Coordinator Results</h1>

    <ul>
        {% for candidate in candidates %}
        {% if candidate.position == "Projects Coordinator" %}
            <li>
                {{ candidate.title }}: {{ candidate.total_borrowed }}
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <hr>
    <h1>Treasurer Results</h1>

    <ul>
        {% for candidate in candidates %}
        {% if candidate.position == "Treasurer" %}
            <li>
                {{ candidate.title }}: {{ candidate.total_borrowed }}
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <hr>
    <h1>Publicity Secretary Results</h1>

    <ul>
        {% for candidate in candidates %}
        {% if candidate.position == "Publicity Secretary" %}
            <li>
                {{ candidate.title }}: {{ candidate.total_borrowed }}
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <hr>
    <h1>Executice Committee Member Results</h1>

    <ul>
        {% for candidate in candidates %}
        {% if candidate.position == "Executice Committee Member" %}
            <li>
                {{ candidate.title }}: {{ candidate.total_borrowed }}
            </li>
        {% endif %}
        {% endfor %}
    </ul>


</div>

    {% endblock %}