BookNest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("",include("library.urls") ),
    path("accounts/",include("accounts.urls")),
    path('admin/', admin.site.urls),
    
]

accounts/urls.py
from django.urls import path
from .import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path("logout/" , views.logout_view , name = "logout")
]

library/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
import static

urlpatterns = [
    path("", views.index, name = "index"),
    path('cart/', views.view_cart, name='view_cart'),
    path('borrow_books/', views.borrow_books, name='borrow_books'),
    path('results/', views.results, name='results'),
    path('view_borrowing_history/', views.view_borrowing_history, name='view_borrowing_history'),
    path('add_to_cart/<int:book_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.contrib.auth.models import BaseUserManager , AbstractBaseUser , PermissionsMixin

class CustomUserManager(BaseUserManager):
    def create_user(self, computer_number, password=None, **extra_fields):
        """
        Creates and saves a User with the given computer_number and password.
        """
        if not computer_number:
            raise ValueError('The Computer Number field must be set')
        if password is None:
            password = "Jumpjet@12"
        user = self.model(computer_number=computer_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, computer_number, password=None, **extra_fields):
        """
        Creates and saves a superuser with the given computer_number and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(computer_number, password, **extra_fields)

    def get_by_natural_key(self, computer_number):
        return self.get(computer_number=computer_number)
    
class CustomUser(AbstractBaseUser , PermissionsMixin):
    computer_number = models.CharField(max_length=100, unique=True)
    # Set password field to null and blank for non-admin users
    password = models.CharField(('password'), max_length=128, null=True, blank=True)
    is_staff = models.BooleanField(default=False)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'computer_number'
    objects = CustomUserManager()

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')

    @property
    def is_anonymous(self):
        return True
    
    @property
    def is_authenticated(self):
        return True
    



class AdminUser(models.Model):
    user_ptr = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        parent_link=True,
    )
    # Add any additional fields for the admin user model here
    pass

    def __str__(self):
        return self.user_ptr.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('computer_number',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['computer_number'].help_text = None
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password2')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login , logout
from .forms import CustomUserCreationForm

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Log the user in
            username = form.cleaned_data.get('computer_number')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('index')

accounts/templates/accounts/signup.html
{% extends "library/index.html" %}

{% load static %}

{% block body %}
    <style>
        .site-form input,
        .site-form textarea {
            display: block;
            margin: 20px 0 0 0;
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
            width: 100%;
            box-sizing: border-box;
            resize: vertical;
        }
        
        .site-form {
            display: block;
            margin: auto;
            margin-top: -2.6rem;
            padding: 20px;
            border-radius: 4px;
            background-color: White;
        }
    </style>
    
    <header class="pt-5" style="margin-top:-8rem;">
        <div class="container pt-4 pt-xl-5">
            <div class="row pt-5">
                <div class="col-md-8 text-center text-md-start mx-auto">
                    <div class="text-center">
                        <center><img src="{% static 'images/unzahssa.jpg'%}" width="250rem"></center>

                        <h1 class="display-4 fw-bold mb-5">UNZAHSSA Voting System&nbsp;</h1>
                        <p class="fs-5 text-muted mb-5">"Your Voice, Your Choice: Building a Better Tomorrow Together"</p>
                        <form class="d-flex justify-content-center flex-wrap" method="post" data-bs-theme="light">
                            {% csrf_token %}
                            <div style = "padding: 1rem; display:block;" class="shadow-lg mb-3"><form class="site-form" action="{% url 'accounts:signup' %}" method="post">
                            <p> We are committed to ensuring the privacy and security of your votes. We want you to know that your votes are confidential, and nobody will know who you voted for. To further protect your voting choices, we require you to create a password for your account.  </p>

                                {{ form.as_p }} 
                                <br>
                                <input style="margin-top:1rem;"  class = "btn btn-primary" type="submit" value="Next">
                            </form></div>
                            
                        </form>
                    </div>
                </div>
                <div class="col-12 col-lg-10 mx-auto">
                    <div class="text-center position-relative"></div>
                </div>
            </div>
        </div>
    </header>
    
{% endblock %}